[metadata]
license_files = LICENSE.txt

[isort]
profile = black
line_length = 100
known_first_party = openedx_webhook_relay
skip = migrations

[coverage:run]
source = openedx_webhook_relay
omit =
    */tests/*
    */migrations/*
    */settings/*

[tool:pytest]
DJANGO_SETTINGS_MODULE = openedx_webhook_relay.tests.settings
testpaths = openedx_webhook_relay/tests
python_files = test_*.py
addopts = -ra
