[tox]
envlist = py311-django{42,52}, quality
skipsdist = true

[testenv]
deps =
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    -r requirements/test.txt
commands =
    pytest --cov=openedx_webhook_relay --cov-report=term-missing --cov-fail-under=90

[testenv:quality]
deps = -r requirements/quality.txt
commands =
    ruff check openedx_webhook_relay
    isort --check-only --diff openedx_webhook_relay
    pylint openedx_webhook_relay
